# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
    - 3.6
    - 3.7
    - 3.8

install:
    - pip install future
    - pip install -e git+https://github.com/achennu/microbenthos#egg=microbenthos[test]

# command to run tests, e.g. python setup.py test
script: pytest tests/


